# imports

In [16]:
import numpy as np
from random import randint
from typing import Union, Any
from enum import Enum

## utils

In [57]:
class InitType(Enum):
    Int = 'int'
    Float = 'float'


def init_rnd_matrix(h: int, w: int, type: InitType, min: Any, max: Any) -> Union[np.matrix, np.array]:
    common_size = h * w
    if min > max:
        raise ValueError()
    
    def float_borders_map(value):
        shift = (max) - min

        return value * shift + min


    min, max = (int(min), int(max)) if type == InitType.Int else (float(min), float(max))
    result = np.random.randint(min, max+1, common_size) if type == InitType.Int else float_borders_map(np.random.rand(common_size))

    if h != 1:
        result = result.reshape(h, w)
    
    return result


In [73]:
print(init_rnd_matrix(10, 10, InitType.Float, 1, 2))

[[1.51428338 1.07276286 1.24233849 1.81665261 1.75600179 1.08905222
  1.9406322  1.12300595 1.76735441 1.76680381]
 [1.33672782 1.25226993 1.84034473 1.66754082 1.23808548 1.94292543
  1.66227734 1.60716915 1.61968785 1.71425605]
 [1.63051594 1.50567196 1.91074512 1.31299081 1.03406959 1.10010048
  1.76993967 1.58559831 1.25993163 1.27823553]
 [1.6844933  1.0510743  1.8743853  1.34916716 1.13304907 1.91020901
  1.26138237 1.83556125 1.67833999 1.43967966]
 [1.92955394 1.73366573 1.91589624 1.46408083 1.52179112 1.70552453
  1.53306514 1.92420035 1.61621776 1.74278958]
 [1.95558409 1.28859886 1.92213023 1.71923771 1.8019417  1.84181506
  1.04674584 1.50908025 1.02765594 1.5348782 ]
 [1.77383029 1.76917549 1.23863575 1.75290861 1.81883453 1.00393068
  1.14003799 1.47848645 1.38331318 1.25024371]
 [1.43280124 1.81670943 1.16425468 1.06529326 1.0045199  1.57691623
  1.4754416  1.8775023  1.59798196 1.25617131]
 [1.88907304 1.76282971 1.37570372 1.2871263  1.26935256 1.57099162
  1.15009295

Задание для студентов: посчитать сумму по строкам, используя матричное произведение.

In [81]:
# np.linalg.
SIZE = 5

matrix = init_rnd_matrix(SIZE, SIZE, InitType.Int, 1, 100)

extra_matrix = np.ones(SIZE).reshape(SIZE, 1)

rows_sum = np.linalg.matmul(matrix, extra_matrix)

print(f"Source matrix:")
print(matrix)
print(f"Result")
print(rows_sum)

Source matrix:
[[56 47 13 74 29]
 [45 22 76 81 61]
 [38 69 35 18 45]
 [32 29 59 72  9]
 [47  3 96 50 10]]
Result
[[219.]
 [285.]
 [205.]
 [201.]
 [206.]]


Выделите строки, у которых ответов "нет" больше, чем ответов "да":

In [92]:
HEIGHT = 10
WIDTH = 5

mtx = init_rnd_matrix(HEIGHT, WIDTH, InitType.Int, 0, 1)

# def convert_to_yes_no(value):
#     if value == 0:
#         return 'No'
#     return 'Yes'


sum = np.sum(mtx, axis=1, keepdims=True)
pick = []

for i, sum_value in enumerate(sum):
    if sum_value * 2 >= WIDTH:
        continue

    pick.append(i)


print("Source matrix 1-Yes 0-No")
print(mtx)
print("Result:")
print(mtx[pick, :])


Source matrix 1-Yes 0-No
[[1 1 1 0 1]
 [1 1 0 0 1]
 [1 1 1 0 0]
 [1 0 0 0 1]
 [0 1 1 1 0]
 [1 1 1 0 1]
 [0 1 0 0 1]
 [1 1 0 0 1]
 [0 0 1 0 1]
 [0 0 0 0 1]]
Result:
[[1 0 0 0 1]
 [0 1 0 0 1]
 [0 0 1 0 1]
 [0 0 0 0 1]]


Вывести квадраты первых десяти натуральных чисел:

In [93]:
def f(x):
    return x * x

print(np.vectorize(f)(np.arange(1, 11)))

[  1   4   9  16  25  36  49  64  81 100]


Перемешать числа натуральные числа от 1 до 10 (воспользуйтесь np.random.permutation):

In [101]:
vector = np.arange(1, 11)

print(vector)
print(np.random.permutation(vector))

[ 1  2  3  4  5  6  7  8  9 10]
[ 8  5 10  3  7  9  1  6  4  2]


Составить таблицу умножения от 1 до 10:

In [129]:
line = np.arange(1, 101)

def gen1(x):
    value = int(x % 10)
    if value == 0:
        return 10
    
    return value

def gen2(x):
    return (x + 10 - 1) // 10


print(np.vectorize(gen1)(line.reshape(10, 10)) * np.vectorize(gen2)(line.reshape(10, 10)))


[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]
